services:
  mysql-orders:
    image: mysql:latest
    restart: always
    container_name: mysql-orders
    hostname: "mysql-orders"
    environment:
      MYSQL_DATABASE: 'orderdb'
      MYSQL_USER: 'orderuser'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '54321'
    ports:
      - '3307:3306'
    networks:
      - my_network


  msorders:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-orders
    environment:
      MYSQL_HOSTNAME: mysql-orders
      MYSQL_PORT: 3306
      MSPRODUCTS_HOSTNAME: ms-products
      MSPRODUCTS_PORT: 8080
      MSCUSTOMERS_HOSTNAME: ms-customers
      MSCUSTOMERS_PORT: 8081
    ports:
      - 8082:8082
    networks:
      - my_network

networks:
  my_network:
    driver: bridge