services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'orderdb'
      MYSQL_USER: 'orderuser'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '54321'
    ports:
      - '3307:3306'
